#logging:
#  level:
#    root: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasksdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

